// packages/docs-preview-react/src/Preview.tsx
import React from 'react';
import type { PreviewProps } from './types';
import './styles/Preview.css';

export const Preview: React.FC<PreviewProps> = ({
  children,
  title,
  description,
  width = 'full',
  background = 'white',
  bordered = false,
}) => {
  const className = `preview preview--${width} preview--${background}${bordered ? ' preview--bordered' : ''}`;

  return (
    <div className={className}>
      {(title || description) && (
        <div className="preview__header">
          {title && <div className="preview__title">{title}</div>}
          {description && <div className="preview__description">{description}</div>}
        </div>
      )}
      <div className="preview__content">{children}</div>
    </div>
  );
};

// packages/docs-preview-vue/src/Preview.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { PreviewProps } from './types';
import './styles/Preview.css';

const props = withDefaults(defineProps<PreviewProps>(), {
  width: 'full',
  background: 'white',
  bordered: false,
});

const className = computed(() => {
  return `preview preview--${props.width} preview--${props.background}${props.bordered ? ' preview--bordered' : ''}`;
});
</script>

<template>
  <div :class="className">
    <div v-if="title || description" class="preview__header">
      <div v-if="title" class="preview__title">{{ title }}</div>
      <div v-if="description" class="preview__description">{{ description }}</div>
    </div>
    <div class="preview__content">
      <slot />
    </div>
  </div>
</template>
