// packages/docs-ui-react/src/EventsTable.tsx
import React from 'react';
import type { EventsTableProps } from './types';

export const EventsTable: React.FC<EventsTableProps> = ({ events }) => {
  if (!events || events.length === 0) {
    return null;
  }

  return (
    <div className="events-table">
      <h4>Events</h4>
      <table>
        <thead>
          <tr>
            <th>Event</th>
            <th>Payload Type</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          {events.map((event) => (
            <tr key={event.name}>
              <td className="event-name">
                <code>{event.name}</code>
              </td>
              <td className="event-payload">
                {event.payload ? (
                  <code>{event.payload.name}</code>
                ) : (
                  <span className="no-payload">void</span>
                )}
              </td>
              <td className="event-description">{event.description || '-'}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

// packages/docs-ui-vue/src/EventsTable.vue
<template>
  <div v-if="hasEvents" class="events-table">
    <h4>Events</h4>
    <table>
      <thead>
        <tr>
          <th>Event</th>
          <th>Payload Type</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="event in events" :key="event.name">
          <td class="event-name">
            <code>{{ event.name }}</code>
          </td>
          <td class="event-payload">
            <code v-if="event.payload">{{ event.payload.name }}</code>
            <span v-else class="no-payload">void</span>
          </td>
          <td class="event-description">
            {{ event.description || '-' }}
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { EventsTableProps } from './types';

const props = defineProps<EventsTableProps>();

const hasEvents = computed(() => {
  return props.events && props.events.length > 0;
});
</script>
