// packages/docs-ui-react/src/HooksPanel.tsx
import React from 'react';
import type { HooksPanelProps } from './types';

export const HooksPanel: React.FC<HooksPanelProps> = ({ hooks }) => {
  if (!hooks || hooks.length === 0) {
    return null;
  }

  return (
    <div className="hooks-panel">
      <h4>Related Hooks</h4>
      <ul className="hooks-list">
        {hooks.map((hook) => (
          <li key={hook} className="hook-item">
            <code>{hook}</code>
          </li>
        ))}
      </ul>
    </div>
  );
};

// packages/docs-ui-vue/src/HooksPanel.vue
<template>
  <div v-if="hasHooks" class="hooks-panel">
    <h4>Related Hooks</h4>
    <ul class="hooks-list">
      <li v-for="hook in hooks" :key="hook" class="hook-item">
        <code>{{ hook }}</code>
      </li>
    </ul>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { HooksPanelProps } from './types';

const props = defineProps<HooksPanelProps>();

const hasHooks = computed(() => {
  return props.hooks && props.hooks.length > 0;
});
</script>
