// packages/docs-ui-react/src/SlotsTable.tsx
import React from 'react';
import type { SlotsTableProps } from './types';

export const SlotsTable: React.FC<SlotsTableProps> = ({ slots }) => {
  if (!slots || slots.length === 0) {
    return null;
  }

  return (
    <div className="slots-table">
      <h4>Slots</h4>
      <table>
        <thead>
          <tr>
            <th>Slot</th>
            <th>Props</th>
          </tr>
        </thead>
        <tbody>
          {slots.map((slot) => (
            <tr key={slot.name}>
              <td className="slot-name">
                <code>{slot.name}</code>
              </td>
              <td className="slot-props">
                {slot.props && Object.keys(slot.props).length > 0 ? (
                  <ul className="slot-props-list">
                    {Object.entries(slot.props).map(([propName, propType]) => (
                      <li key={propName}>
                        <code>{propName}</code>: <code>{propType.name}</code>
                      </li>
                    ))}
                  </ul>
                ) : (
                  <span className="no-props">No props</span>
                )}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

// packages/docs-ui-vue/src/SlotsTable.vue
<template>
  <div v-if="hasSlots" class="slots-table">
    <h4>Slots</h4>
    <table>
      <thead>
        <tr>
          <th>Slot</th>
          <th>Props</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="slot in slots" :key="slot.name">
          <td class="slot-name">
            <code>{{ slot.name }}</code>
          </td>
          <td class="slot-props">
            <ul v-if="hasSlotProps(slot)" class="slot-props-list">
              <li v-for="(propType, propName) in slot.props" :key="propName">
                <code>{{ propName }}</code
                >: <code>{{ propType.name }}</code>
              </li>
            </ul>
            <span v-else class="no-props">No props</span>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { SlotsTableProps } from './types';

const props = defineProps<SlotsTableProps>();

const hasSlots = computed(() => {
  return props.slots && props.slots.length > 0;
});

const hasSlotProps = (slot: any) => {
  return slot.props && Object.keys(slot.props).length > 0;
};
</script>
