// packages/react-hooks/src/useToggle/demos/useToggleAdvanced.demo.tsx
import { useToggle } from '../../useToggle';

export default function UseToggleAdvancedDemo() {
  const toggle1 = useToggle({
    initialValue: true,
  });

  const toggle2 = useToggle<'light' | 'dark'>({
    initialValue: 'light',
    trueValue: 'light',
    falseValue: 'dark',
  });

  const toggle3 = useToggle<1 | 0>({
    initialValue: 0,
    trueValue: 1,
    falseValue: 0,
  });

  return (
    <div
      style={{
        padding: '20px',
        border: '1px solid #e8e8e8',
        borderRadius: '8px',
        backgroundColor: '#fff',
      }}
    >
      <div style={{ marginBottom: '20px' }}>
        <h3 style={{ margin: '0 0 8px 0', fontSize: '16px', fontWeight: 600, color: '#333' }}>
          高级用法
        </h3>
        <p style={{ margin: 0, fontSize: '14px', color: '#666', lineHeight: 1.5 }}>
          展示 useToggle hook 的自定义初始值和自定义值类型。
        </p>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            gap: '20px',
            padding: '16px',
            background: '#fafafa',
            borderRadius: '8px',
          }}
        >
          <h4 style={{ margin: 0, fontSize: '14px', fontWeight: 600, color: '#333' }}>
            默认值：true
          </h4>
          <div
            style={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
              padding: '20px',
              background: '#f5f5f5',
              borderRadius: '8px',
              marginBottom: '12px',
            }}
          >
            <div
              style={{
                width: '80px',
                height: '80px',
                borderRadius: '50%',
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center',
                fontSize: '24px',
                fontWeight: 'bold',
                color: '#fff',
                background: toggle1.state ? '#52c41a' : '#bfbfbf',
                transition: 'all 0.3s',
              }}
            >
              {toggle1.state ? '开' : '关'}
            </div>
          </div>
          <div style={{ display: 'flex', justifyContent: 'center' }}>
            <button
              onClick={() => toggle1.toggle()}
              style={{
                padding: '8px 16px',
                border: '1px solid #d9d9d9',
                borderRadius: '4px',
                background: '#fff',
                color: '#333',
                fontSize: '14px',
                cursor: 'pointer',
                transition: 'all 0.3s',
              }}
            >
              切换
            </button>
          </div>
        </div>

        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            gap: '20px',
            padding: '16px',
            background: '#fafafa',
            borderRadius: '8px',
          }}
        >
          <h4 style={{ margin: 0, fontSize: '14px', fontWeight: 600, color: '#333' }}>
            字符串类型：light/dark
          </h4>
          <div
            style={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
              padding: '20px',
              background: '#f5f5f5',
              borderRadius: '8px',
              marginBottom: '12px',
            }}
          >
            <div
              style={{
                width: '80px',
                height: '80px',
                borderRadius: '50%',
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center',
                fontSize: '24px',
                fontWeight: 'bold',
                color: '#fff',
                background: toggle2.state === 'light' ? '#52c41a' : '#bfbfbf',
                transition: 'all 0.3s',
              }}
            >
              {toggle2.state}
            </div>
          </div>
          <div style={{ display: 'flex', justifyContent: 'center' }}>
            <button
              onClick={() => toggle2.toggle()}
              style={{
                padding: '8px 16px',
                border: '1px solid #d9d9d9',
                borderRadius: '4px',
                background: '#fff',
                color: '#333',
                fontSize: '14px',
                cursor: 'pointer',
                transition: 'all 0.3s',
              }}
            >
              切换
            </button>
          </div>
        </div>

        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            gap: '20px',
            padding: '16px',
            background: '#fafafa',
            borderRadius: '8px',
          }}
        >
          <h4 style={{ margin: 0, fontSize: '14px', fontWeight: 600, color: '#333' }}>
            数字类型：1/0
          </h4>
          <div
            style={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
              padding: '20px',
              background: '#f5f5f5',
              borderRadius: '8px',
              marginBottom: '12px',
            }}
          >
            <div
              style={{
                width: '80px',
                height: '80px',
                borderRadius: '50%',
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center',
                fontSize: '24px',
                fontWeight: 'bold',
                color: '#fff',
                background: toggle3.state === 1 ? '#52c41a' : '#bfbfbf',
                transition: 'all 0.3s',
              }}
            >
              {toggle3.state}
            </div>
          </div>
          <div style={{ display: 'flex', justifyContent: 'center' }}>
            <button
              onClick={() => toggle3.toggle()}
              style={{
                padding: '8px 16px',
                border: '1px solid #d9d9d9',
                borderRadius: '4px',
                background: '#fff',
                color: '#333',
                fontSize: '14px',
                cursor: 'pointer',
                transition: 'all 0.3s',
              }}
            >
              切换
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

// packages/vue-hooks/src/useToggle/demos/useToggleAdvanced.demo.vue
<script setup lang="ts">
import { useToggle } from '../../useToggle';

const title = '高级用法';
const description = '展示 useToggle hook 的自定义初始值和自定义值类型。';

const toggle1 = useToggle({
  initialValue: true,
});

const toggle2 = useToggle({
  initialValue: 'light',
  trueValue: 'light',
  falseValue: 'dark',
});

const toggle3 = useToggle({
  initialValue: 0,
  trueValue: 1,
  falseValue: 0,
});
</script>

<template>
  <div class="demo-container">
    <div class="demo-title">
      <h3>{{ title }}</h3>
      <p>{{ description }}</p>
    </div>

    <div class="demo-content">
      <div class="toggle-item">
        <h4>默认值：true</h4>
        <div class="toggle-display">
          <div class="toggle-indicator" :class="{ active: toggle1.state }">
            {{ toggle1.state ? '开' : '关' }}
          </div>
        </div>
        <div class="toggle-controls">
          <button class="btn" @click="toggle1.toggle">切换</button>
        </div>
      </div>

      <div class="toggle-item">
        <h4>字符串类型：light/dark</h4>
        <div class="toggle-display">
          <div class="toggle-indicator" :class="{ active: toggle2.state === 'light' }">
            {{ toggle2.state }}
          </div>
        </div>
        <div class="toggle-controls">
          <button class="btn" @click="toggle2.toggle">切换</button>
        </div>
      </div>

      <div class="toggle-item">
        <h4>数字类型：1/0</h4>
        <div class="toggle-display">
          <div class="toggle-indicator" :class="{ active: toggle3.state === 1 }">
            {{ toggle3.state }}
          </div>
        </div>
        <div class="toggle-controls">
          <button class="btn" @click="toggle3.toggle">切换</button>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.demo-container {
  padding: 20px;
  border: 1px solid #e8e8e8;
  border-radius: 8px;
  background-color: #fff;
}

.demo-title {
  margin-bottom: 20px;
}

.demo-title h3 {
  margin: 0 0 8px 0;
  font-size: 16px;
  font-weight: 600;
  color: #333;
}

.demo-title p {
  margin: 0;
  font-size: 14px;
  color: #666;
  line-height: 1.5;
}

.demo-content {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.toggle-item h4 {
  margin: 0 0 12px 0;
  font-size: 14px;
  font-weight: 600;
  color: #333;
}

.toggle-display {
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 20px;
  background: #f5f5f5;
  border-radius: 8px;
  margin-bottom: 12px;
}

.toggle-indicator {
  width: 80px;
  height: 80px;
  border-radius: 50%;
  display: flex;
  justify-content: center;
  align-items: center;
  font-size: 24px;
  font-weight: bold;
  color: #fff;
  background: #bfbfbf;
  transition: all 0.3s;
}

.toggle-indicator.active {
  background: #52c41a;
}

.toggle-controls {
  display: flex;
  justify-content: center;
  gap: 12px;
}

.btn {
  padding: 8px 16px;
  border: 1px solid #d9d9d9;
  border-radius: 4px;
  background: #fff;
  color: #333;
  font-size: 14px;
  cursor: pointer;
  transition: all 0.3s;
}

.btn:hover {
  border-color: #1890ff;
  color: #1890ff;
}
</style>
