// packages/docs-preview-vue/src/PreviewContainer.vue
<script setup lang="ts">
import Preview from './Preview.vue';
import CodeBlock from './CodeBlock.vue';
import type { PreviewContainerProps } from './types';
import './styles/PreviewContainer.css';

withDefaults(defineProps<PreviewContainerProps>(), {
  language: 'vue',
  showLineNumbers: false,
  showCopy: true,
  codeTitle: '',
  width: 'full',
  background: 'white',
  bordered: false,
});
</script>

<template>
  <div class="preview-container">
    <Preview :width="width" :background="background" :bordered="bordered">
      <slot />
    </Preview>
    <CodeBlock
      :code="code"
      :language="language"
      :show-line-numbers="showLineNumbers"
      :show-copy="showCopy"
      :title="codeTitle"
    />
  </div>
</template>

// packages/docs-preview-react/src/PreviewContainer.tsx
import React from 'react';
import type { PreviewContainerProps } from './types';
import { Preview } from './Preview';
import { CodeBlock } from './CodeBlock';
import './styles/PreviewContainer.css';

export const PreviewContainer: React.FC<PreviewContainerProps> = ({
  children,
  code,
  language = 'tsx',
  showLineNumbers = false,
  showCopy = true,
  codeTitle,
  width = 'full',
  background = 'white',
  bordered = false,
}) => {
  return (
    <div className="preview-container">
      <Preview width={width} background={background} bordered={bordered}>
        {children}
      </Preview>
      <CodeBlock
        code={code}
        language={language}
        showLineNumbers={showLineNumbers}
        showCopy={showCopy}
        title={codeTitle}
      />
    </div>
  );
};
