// packages/docs-ui-vue/src/DemoLayout.vue
<template>
  <div class="demo-layout">
    <h3 v-if="title" class="demo-title">
      {{ title }}
    </h3>
    <p v-if="description" class="demo-description">
      {{ description }}
    </p>
    <div class="demo-content">
      <slot />
    </div>
  </div>
</template>

<script setup lang="ts">
import type { DemoLayoutProps } from './types';

defineProps<DemoLayoutProps>();
</script>

// packages/docs-ui-react/src/DemoLayout.tsx
import React from 'react';
import type { DemoLayoutProps } from './types';

export const DemoLayout: React.FC<DemoLayoutProps> = ({ title, description, children }) => {
  return (
    <div className="demo-layout">
      {title && <h3 className="demo-title">{title}</h3>}
      {description && <p className="demo-description">{description}</p>}
      <div className="demo-content">{children}</div>
    </div>
  );
};
